# https://www.home-assistant.io/integrations/binary_sensor.rest
binary_sensor:
  - platform: rest
    name: bestagons_state
    resource: http://192.168.1.28/system

# https://www.home-assistant.io/integrations/rest_command/
rest_command:
  bestagons_system_state_off:
    url: http://192.168.1.28/system
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "off=off"

  bestagons_system_state_on:
    url: http://192.168.1.28/system
    method: POST
    content_type: "application/x-www-form-urlencoded"
    payload: "on=on"

# https://www.home-assistant.io/integrations/switch.template/
switch:
  - platform: template
    switches:
      bestagons:
        friendly_name: "Bestagons!"
        value_template: "{{ is_state('binary_sensor.bestagons_state', 'on') }}"
        turn_on:
          - service: rest_command.bestagons_system_state_on
          - service: homeassistant.update_entity
            target:
              entity_id: binary_sensor.bestagons_state

        turn_off:
          - service: rest_command.bestagons_system_state_off
          - service: homeassistant.update_entity
            target:
              entity_id: binary_sensor.bestagons_state
