# https://github.com/dr-prodigy/python-holidays/blob/master/holidays/countries/united_states.py

binary_sensor:
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    remove_holidays:
      - "Veterans Day"
      - "New Year's Eve"
