- id: notify-when-motion
  alias: Notify when motion
  description: when motion
  trigger:
    - type: motion
      platform: device
      device_id: 4b3fd83133d936fcc5df9d2ceb599bb1
      entity_id: binary_sensor.samjin_motion_7e3f0801_ias_zone
      domain: binary_sensor
  condition: []
  action:
    - service: notify.mobile_app_travis_pixel_4a
      data:
        message: motion in bedroom!!!
        title: Motion Detected
  mode: single
- id: welcome-home-travis
  alias: Welcome home Travis
  trigger:
    - platform: zone
      entity_id: person.travis
      zone: zone.home
      event: enter
  action:
    - service: notify.mobile_app_travis_pixel_4a
      data:
        message: Welcome home, Travis
  mode: single
- id: bye-from-home
  alias: Bye from home
  description: ""
  trigger:
    - platform: zone
      entity_id: person.travis
      zone: zone.home
      event: leave
  action:
    - service: notify.mobile_app_travis_pixel_4a
      data:
        message: Bye, Travis
  mode: single
