# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
automation split: !include_dir_list ./automations
script: !include scripts.yaml
scene: !include scenes.yaml

zwave:
  usb_path: /dev/ttyUSB0

binary_sensor:
  - platform: workday
    country: US
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]

rest_command:
  slack_presense:
    url: https://slack.com/api/users.setPresence
    method: POST
    content_type: application/json
    headers:
      authorization: !secret slack_auth_header
    payload: '{"presence": "{{presence}}"}'

cover:
  - platform: opengarage
    covers:
      garage:
        host: 192.168.87.26
        device_key: !secret opengarage_device_key
        name: Garage Door
