id: background-noise
alias: Background Noise

trigger:
  - platform: time
    at: "22:00:00"
  - platform: time
    at: "10:00:00"
  - platform: time
    at: "19:00:00"

action:
  service: script.background_noise_start

mode: single
