id: set-mailbox-state
alias: Set Mailbox State
description: >-
  Toggle the input_boolean based on the value of the mailbox tilt sensor.

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: "28:6d:97:00:01:06:8f:8c"

condition:
  - condition: template
    value_template: '{{ trigger.event.data.args.attribute_name == "x_axis" }}'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.args.value > -550 }}"
        sequence:
          - service: input_boolean.turn_on
            entity_id: input_boolean.mailbox_open
    default:
      - service: input_boolean.turn_off
        entity_id: input_boolean.mailbox_open

mode: queued
max: 20
