id: travis-meeting-on
alias: Travis Meeting On

trigger:
  - platform: state
    entity_id: binary_sensor.traviss_macbook_pro_camera_in_use
    to: "on"

action:
  - service: light.turn_on
    target:
      entity_id: light.office_wall_light1
    data:
      transition: 0
      brightness_pct: 100
      hs_color:
        - 300 # pink
        - 100
  - service: light.turn_on
    target:
      entity_id: light.office_wall_light2
    data:
      transition: 0
      brightness_pct: 100
      hs_color:
        - 240 # blue
        - 100
  - service: light.turn_on
    target:
      entity_id: light.on_air_sign
    data:
      transition: 0
      brightness_pct: 20
      hs_color:
        - 120 # green
        - 100
mode: single
