id: travis-meeting-on
alias: Travis Meeting On
description: >-
  Turn on "on air" light, and the webcam light when the webcam turns on

trigger:
  - platform: state
    entity_id: binary_sensor.traviss_macbook_pro_camera_in_use
    to: "on"

action:
  - service: light.turn_on
    target:
      entity_id: light.on_air_sign
    data:
      transition: 0
      brightness_pct: 20
      hs_color:
        - 120 # green
        - 100

  - service: switch.turn_on
    target:
      entity_id: switch.webcam_light

mode: single
