id: travis-meeting-off
alias: Travis Meeting Off

trigger:
  - platform: state
    entity_id: binary_sensor.traviss_macbook_pro_camera_in_use
    to: "off"

action:
  - service: light.turn_off
    target:
      entity_id:
        - light.office_wall_light1
        - light.office_wall_light2
        - light.on_air_sign

mode: single
