id: travis-meeting-off
alias: Travis Meeting Off
description: >-
  Turn off "on air" light, and the webcam light when the webcam turns off

trigger:
  - platform: state
    entity_id: binary_sensor.zoom_travis
    to: "off"

action:
  - service: light.turn_off
    target:
      entity_id:
        - light.on_air_sign

  - service: switch.turn_off
    target:
      entity_id: switch.webcam_light

mode: single
