id: ev-low-battery-notification-dismiss
alias: EV low battery notification - dismiss
description: >-
  Dismisses the low battery notificaiton

trigger:
  - platform: numeric_state
    entity_id: sensor.handsome_jack_range_sensor
    above: 100

  - platform: state
    entity_id: binary_sensor.handsome_jack_charger_sensor
    to: "on"

action:
  - service: notify.notify
    data:
      message: "clear_notification"
      data:
        tag: ev

mode: single
