id: trash-recycle-notification
alias: Trash and Recycle notification
description: >-
  Alert devices when the trash and recycle bins need to go out

trigger:
  - platform: time
    at: "17:00"
  - platform: time
    at: "19:00"
  - platform: time
    at: "21:00"
  - platform: time
    at: "22:00"

condition:
  - condition: time
    weekday:
      - thu
  - condition: state
    entity_id: binary_sensor.recycle_week
    state: "on"

  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.trash_bin
        state: "on"
      - condition: state
        entity_id: binary_sensor.recycle_bin
        state: "on"

action:
  - service: notify.notify
    data:
      title: TRASH and RECYCLE bins
      message: "The trash and recycle bins need to go out"
      data:
        color: green
        sticky: false
        url: "/lovelace/garage"
        clickAction: "/lovelace/garage"

mode: single
