esphome:
  name: trash-bin
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Trash-Bin Fallback Hotspot"
    password: !secret wifi_password

captive_portal:


sensor:
  - platform: ultrasonic
    name: "Trash Bin"
    echo_pin: GPIO2
    trigger_pin: GPIO0
    update_interval: 5s

  - platform: ultrasonic
    name: "Recycle Bin"
    echo_pin: GPIO4
    trigger_pin: GPIO16
    update_interval: 5s
